sitture/env-config

- README.md
- src/main/java/com/sitture/env/config/EnvConfig.java
- src/test/java/com/sitture/env/config/EnvConfigTest.java
@haroon-sheikh  Please review 👍 
For issue #15 
Added a method to clear a specified property.
> added EnvConfig.clear method

- .circleci/config.yml
- .circleci/run_tests.sh
> Updates the maven command

- README.md
- pom.xml
- src/main/java/com/github/sitture/env/config/ConfigException.java
- src/main/java/com/github/sitture/env/config/ConfigLoader.java
- src/main/java/com/github/sitture/env/config/EnvConfig.java
- src/main/java/com/github/sitture/env/config/EnvironmentVariables.java
- src/main/java/com/github/sitture/env/config/MissingVariableException.java
- src/main/resources/log4j.properties
- src/test/java/com/github/sitture/env/config/EnvConfigTest.java
> Moves package under com.github

- CHANGELOG.md
- src/main/java/com/github/sitture/env/config/ConfigLoader.java
- src/main/java/com/github/sitture/env/config/EnvironmentVariables.java
- src/main/java/com/github/sitture/env/config/KeePassEntries.java
- src/test/java/com/github/sitture/env/config/EnvConfigTest.java
> Updates the format of keepass properties added to env map

- CHANGELOG.md
- README.md
- pom.xml
- src/main/java/com/github/sitture/env/config/EnvironmentVariables.java
- src/test/java/com/github/sitture/env/config/EnvConfigTest.java
> adds the raw environments as well as processed lowercased keys

- .gitignore
- CHANGELOG.md
- pom.xml
- src/main/java/com/github/sitture/env/config/ConfigException.java
- src/main/java/com/github/sitture/env/config/ConfigLoader.java
- src/main/java/com/github/sitture/env/config/EnvConfig.java
- src/main/java/com/github/sitture/env/config/EnvironmentVariables.java
- src/main/java/com/github/sitture/env/config/KeePassEntries.java
- src/main/java/com/github/sitture/env/config/MissingVariableException.java
- src/main/resources/config/checkstyle/checkstyle.xml
- src/main/resources/config/pmd/rulesets.xml
- src/test/java/com/github/sitture/env/config/EnvConfigTest.java
> Updates to use the latest rulesets for pmd/checkstyle

- CHANGELOG.md
- README.md
- src/main/java/com/github/sitture/env/config/EnvConfig.java
- src/test/java/com/github/sitture/env/config/EnvConfigTest.java
> Updates method to getOrThrow(property) for getting a required property

- CHANGELOG.md
- pom.xml
- src/main/java/com/github/sitture/env/config/ConfigLoader.java
- src/main/java/com/github/sitture/env/config/filter/ConfigFileList.java
- src/main/java/com/github/sitture/env/config/utils/BuildDirUtils.java
- src/main/java/com/github/sitture/env/config/utils/PropertyUtils.java
- src/test/java/com/github/sitture/env/config/utils/BuildDirUtilsTest.java
> Update config.dir to accept relative and absolute paths

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- CHANGELOG.md
> fixes markdown lint issues with github templates

- .github/workflows/github-publish.yml
- .github/workflows/maven-build.yml
- .github/workflows/maven-publish.yml
- CHANGELOG.md
- pom.xml
- src/test/java/com/github/sitture/env/config/EnvConfigTest.java
> Updating checkstyle and pmd plugins to latest

- pom.xml
- src/main/java/com/github/sitture/env/config/EnvConfig.java
> Updating to latest version of checkstyle 10.2

- CHANGELOG.md
- README.md
- config/sample-profiles/default/prof1/prof1.properties
- pom.xml
- src/main/java/com/github/sitture/envconfig/EnvConfig.java
- src/main/java/com/github/sitture/envconfig/EnvConfigFileList.java
- src/main/java/com/github/sitture/envconfig/EnvConfigLoader.java
- src/main/java/com/github/sitture/envconfig/EnvConfigProfileFileList.java
- src/main/java/com/github/sitture/envconfig/EnvConfigProperties.java
- src/main/java/com/github/sitture/envconfig/EnvConfigUtils.java
- src/test/java/com/github/sitture/envconfig/EnvConfigProfileTest.java
- src/test/java/com/github/sitture/envconfig/EnvConfigPropertiesTest.java
- src/test/java/com/github/sitture/envconfig/EnvConfigTest.java
- src/test/java/com/github/sitture/envconfig/EnvConfigUtilsTest.java
> Fixes an issue with default environment loading more than once

- CHANGELOG.md
- pom.xml
- src/main/java/com/github/sitture/envconfig/EnvConfigLoader.java
- src/test/java/com/github/sitture/envconfig/EnvConfigProfileTest.java
- src/test/java/com/github/sitture/envconfig/EnvConfigTest.java
> Fixes an issue when env var and parent/default env values are same

- CHANGELOG.md
- pom.xml
- src/main/java/com/github/sitture/envconfig/EnvConfigLoader.java
> Removes duplicate exception from EnvConfigLoader

- CHANGELOG.md
- src/main/java/com/github/sitture/envconfig/EnvConfigLoader.java
- src/test/java/com/github/sitture/envconfig/EnvConfigTest.java
> System environment should now take precedence over keepass

- pom.xml
- src/main/java/com/github/sitture/envconfig/EnvConfig.java
- src/main/java/com/github/sitture/envconfig/EnvConfigLoader.java
- src/main/java/com/github/sitture/envconfig/KeePassEntries.java
- src/main/resources/config/pmd/rulesets.xml
> Updates pmd rulesets

- CHANGELOG.md
- pom.xml
- src/main/java/com/github/sitture/envconfig/EnvConfigLoader.java
- src/test/java/com/github/sitture/envconfig/EnvConfigPrecedenceTest.java
- src/test/java/com/github/sitture/envconfig/EnvConfigTest.java
> Skip env vars if key=value pair in env/properties are same

- .github/dependabot.yml
> Updates dependabot to manage github actions

- .github/workflows/github-publish.yml
- .github/workflows/maven-publish.yml
- CHANGELOG.md
- pom.xml
Adding reproducible builds configuration
Fixes #147
> Adding reproducible builds configuration

- CHANGELOG.md
- pom.xml
- src/main/java/com/github/sitture/envconfig/EnvConfigLoader.java
- src/main/java/com/github/sitture/envconfig/VaultConfiguration.java
- src/main/resources/config/pmd/rulesets.xml
- src/test/java/com/github/sitture/envconfig/EnvConfigPrecedenceTest.java
- src/test/java/com/github/sitture/envconfig/EnvConfigProfileTest.java
- src/test/java/com/github/sitture/envconfig/EnvConfigPropertiesTest.java
- src/test/java/com/github/sitture/envconfig/EnvConfigVaultTest.java
> Updates to latest version of pmd@v7

- CHANGELOG.md
- README.md
- pom.xml
- src/main/java/com/github/sitture/envconfig/EnvConfig.java
- src/main/java/com/github/sitture/envconfig/EnvConfigFileList.java
- src/main/java/com/github/sitture/envconfig/EnvConfigKey.java
- src/main/java/com/github/sitture/envconfig/EnvConfigLoader.java
- src/main/java/com/github/sitture/envconfig/EnvConfigProperties.java
- src/main/java/com/github/sitture/envconfig/EnvConfigUtils.java
- src/main/java/com/github/sitture/envconfig/EnvConfigVaultProperties.java
- src/main/java/com/github/sitture/envconfig/EnvironmentVariables.java
- src/main/java/com/github/sitture/envconfig/KeepassConfiguration.java
- src/main/java/com/github/sitture/envconfig/VaultConfiguration.java
- src/test/java/com/github/sitture/envconfig/EnvConfigPrecedenceTest.java
- src/test/java/com/github/sitture/envconfig/EnvConfigProfileTest.java
- src/test/java/com/github/sitture/envconfig/EnvConfigPropertiesTest.java
- src/test/java/com/github/sitture/envconfig/EnvConfigTest.java
- src/test/java/com/github/sitture/envconfig/EnvConfigUtilsTest.java
- src/test/java/com/github/sitture/envconfig/EnvConfigVaultTest.java
- src/test/java/com/github/sitture/envconfig/VaultConfigurationTest.java
> Adds ability to specify a default secret path when loading from vault

- pom.xml
lock maven-jar-plugin version, instead of inheriting version from Maven used: ensures it is a version that provides Reproducible Builds
> lock m-jar-p version

- CHANGELOG.md
- pom.xml
- src/main/java/com/github/sitture/envconfig/KeepassConfiguration.java
> Changes for moving to use jorabin/KeePassJava2

- CHANGELOG.md
- pom.xml
- src/main/resources/config/pmd/rulesets.xml
> Excluding commons-collections dependency to resolve vulnerabilities

- CHANGELOG.md
- pom.xml
- src/main/java/com/github/sitture/envconfig/EnvConfigProperties.java
- src/main/java/com/github/sitture/envconfig/EnvConfigUtils.java
- src/main/java/com/github/sitture/envconfig/KeepassConfiguration.java
- src/test/java/com/github/sitture/envconfig/EnvConfigKeyTest.java
- src/test/java/com/github/sitture/envconfig/EnvConfigUtilsTest.java
> Fixes an issue with resolving config properties

- CHANGELOG.md
- pom.xml
- Excludes org.linguafranca.pwdb:util dependency as it's only used by the tests
> Excludes org.linguafranca.pwdb:util dependency

- pom.xml
> Adds missing property to fix a java compiler warning

- .github/workflows/maven-publish.yml
- pom.xml
> Updates for publishing to central repo

- pom.xml
- src/main/java/com/github/sitture/envconfig/EnvConfigException.java
- src/main/java/com/github/sitture/envconfig/EnvConfigProperties.java
- src/main/java/com/github/sitture/envconfig/EnvConfigUtils.java
- src/main/java/com/github/sitture/envconfig/KeepassConfiguration.java
- src/main/java/com/github/sitture/envconfig/VaultConfiguration.java
- src/test/java/com/github/sitture/envconfig/EnvConfigPropertiesTest.java
- src/test/java/com/github/sitture/envconfig/EnvConfigTest.java
- src/test/java/com/github/sitture/envconfig/EnvConfigUtilsTest.java
- src/test/java/com/github/sitture/envconfig/EnvConfigVaultTest.java
- src/test/java/com/github/sitture/envconfig/VaultConfigurationTest.java
Changes from java17 openrewrite recipe
> Changes from java17 openrewrite recipe
